name: Neovim
on:
  pull_request: ~
  push:
    paths-ignore:
      - "*.md"
    branches:
      - main

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        neovim_tag:
          [
            "v0.8.0",
            "v0.8.1",
            "v0.8.2",
            "v0.8.3",
            "v0.9.0",
            "stable",
            "nightly",
          ]
    name: Ubuntu nvim-${{ matrix.neovim_tag }}

    steps:
      - uses: actions/checkout@v3
      - name: Install Neovim
        uses: MunifTanjim/setup-neovim-action@v1
        with:
          tag: ${{ matrix.neovim_tag }}
      - name: Run neovim
        run: |
          nvim --version
          nvim --headless -u test/init.lua +q
  macos:
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        neovim_tag:
          [
            "v0.8.0",
            "v0.8.1",
            "v0.8.2",
            "v0.8.3",
            "v0.9.0",
            "stable",
            "nightly",
          ]
    name: MacOS nvim-${{ matrix.neovim_tag }}

    steps:
      - uses: actions/checkout@v3
      - name: Install Neovim
        uses: MunifTanjim/setup-neovim-action@v1
        with:
          tag: ${{ matrix.neovim_tag }}
      - name: Run neovim
        run: |
          nvim --version
          nvim --headless -u test/init.lua +q
  windows:
    name: Windows nvim-nightly
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Neovim
        run: |
          C:\msys64\usr\bin\wget.exe -q https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip
          7z x nvim-win64.zip
          Add-Content $env:GITHUB_PATH ".\nvim-win64\bin\"
      - name: Run neovim
        run: |
          nvim --version
          nvim --headless -u test/init.lua +q
