name: Tests
on:
  pull_request: ~
  push:
    paths:
      - "lua/*"
      - "test/*"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        neovim_tag:
          [
            "v0.8.0",
            "v0.8.1",
            "v0.8.2",
            "v0.8.3",
            "v0.9.0",
            "stable",
            "nightly",
          ]
    name: Tests Neovim ${{ matrix.neovim_tag }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Neovim
        uses: MunifTanjim/setup-neovim-action@v1
        with:
          tag: ${{ matrix.neovim_tag }}

      - name: Install plenary
        run: |
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim test/plenary

      - name: Run tests
        run: |
          nvim --version
          [ ! -d test ] && exit 0
          nvim --headless --noplugin -u test/minimal_init.vim -c "PlenaryBustedDirectory ./test/github-theme { minimal_init = './test/minimal_init.vim', sequential = true}"
